In [1]:
import pandas as pd
import numpy as np

In [58]:
a = [1., 0., 0., 0., 1.]

In [3]:
b = [2, 4]

In [6]:
df = pd.DataFrame(a, columns=['a'])

In [14]:
df.a.isin(b)

0    False
1     True
2    False
3     True
4    False
Name: a, dtype: bool

In [8]:
ind = df.a.isin(n) & df.user_id.isin(df2.user_id)

a
0  1
1  2
2  3
3  4
4  5

In [16]:
df[df.a.isin(b)]

a
1  2
3  4

In [59]:
a = np.array(a).astype(float) / np.linalg.norm(a)

In [41]:
from sklearn import preprocessing

In [45]:
a = preprocessing.Normalizer(a)

In [49]:
a

array([ 0.70710678,  0.        ,  0.        ,  0.        ,  0.70710678])

In [39]:
a = [1, 2, 3, 4, 5]

In [37]:
a = preprocessing.normalize(np.array(a).astype(float))

In [60]:
s = preprocessing.scale(a)

In [61]:
s

array([ 1.22474487, -0.81649658, -0.81649658, -0.81649658,  1.22474487])

In [64]:
a = np.array(s).astype(float) / np.linalg.norm(s)

In [65]:
a

array([ 0.54772256, -0.36514837, -0.36514837, -0.36514837,  0.54772256])